[Sleep]
AllowSuspend=yes
AllowHibernation=yes
AllowSuspendThenHibernate=yes
AllowHybridSleep=no
HibernateDelaySec=1h
SuspendEstimationSec=1h
SuspendState=mem
SuspendMode=suspend
MemorySleepMode=deep
HibernateState=disk
HibernateMode=platform shutdown
