[Sleep]
AllowSuspend=yes
AllowHibernation=yes
AllowSuspendThenHibernate=yes
AllowHybridSleep=no
HibernateDelaySec=1h
SuspendEstimationSec=1h
SuspendState=mem
MemorySleepMode=deep
HibernateMode=platform shutdown
