# 2026-10-04 hardening; none of these cost performance
kernel.kptr_restrict = 2
kernel.kexec_load_disabled = 1
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
dev.tty.ldisc_autoload = 0
