# Conversion toolbox (runs from RAM on the T480) and root file system of the QEMU replica.
FROM alpine:3.22
RUN apk add --no-cache cryptsetup e2fsprogs e2fsprogs-extra sfdisk util-linux-misc blkid partx keyutils tpm2-tools tpm2-tss-tcti-device xxd device-mapper && \
    rm -rf /var/cache/apk/*
