/* GENERATED by theme-sync.sh from theme/palette.conf — do not hand-edit. */
static const char black[]       = "#101010"; // surfaces: bar, window bg
static const char gray2[]       = "#3a3a3a"; // unfocused window border / chrome
static const char gray3[]       = "#e4e4e4"; // bar text, active-tag block
static const char gray4[]       = "#f0f0f0"; // selected text / active tag fill
static const char blue[]        = "#1e1e1e"; // raised surface: selected tab, panels
static const char green[]       = "#b8b8b8"; // occupied tag 3
static const char red[]         = "#c8c8c8"; // alert slot, grayscale only
static const char orange[]      = "#cfcfcf"; // occupied tag 2
static const char yellow[]      = "#a8a8a8"; // occupied tag 4 / button accent
static const char pink[]        = "#6e6e6e"; // vacant tag text (muted)
static const char col_borderbar[]  = "#101010"; // inner border
static const char white[]       = "#ededed"; // focused border / occupied tag 1
